name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:

permissions:
  contents: read

jobs:
  web:
    name: Web Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm lint --filter web

      - name: Build
        run: pnpm build --filter web

  api:
    name: API Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: apps/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest pytest-asyncio

      - name: Lint
        working-directory: apps/api
        run: ruff check app

      - name: Test
        working-directory: apps/api
        run: pytest

  terraform:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Format Check
        working-directory: infra/terraform
        run: terraform fmt -check

      - name: Init
        working-directory: infra/terraform
        run: terraform init -backend=false

      - name: Validate
        working-directory: infra/terraform
        run: terraform validate
